#! /bin/bash
sudo apt-get update && sudo apt-get install docker.io -y
sudo docker ps
sudo docker pull busybox
sudo docker tag busybox localhost:5000/busybox

   
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
sudo apt install unzip
unzip awscliv2.zip
sudo ./aws/install
aws --version
wget https://raw.githubusercontent.com/praveensiddu/container-registry/master/aws/registry.sh
